language: node_js

node_js:
  - "8"

install:
- travis_retry npm install
- npm run build

script:
  - npm run test

deploy:
    provider: script
    script:
      - npm install
      - npx semantic-release
    on:
        branch: master
