language: node_js

node_js:
  - "8"

branches:
    only:
      - master

install:
- travis_retry npm install

script:
    - npm run test

deploy:
    provider: script
    script:
      - npx semantic-release
